language: java
jdk: oraclejdk7
before_install:
    - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
    - tar xzf android-sdk_r22.3-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    - echo y | android update sdk --filter platform-tools,android-18,addon-google_apis-google-18,extra-android-m2repository --no-ui --force
script:
  - TERM=dumb ./gradlew assembleDebug :UnitTestsRobolectric:testDebug :ComponentTestsRobolectric:testDebug